export const MODAL_ACTION_CLOSE = 'MODAL_ACTION_CLOSE'
export const MODAL_ACTION_CONFIRM = 'MODAL_ACTION_CONFIRM'
export const SUBMIT_MODAL_EDIT = 'SUBMIT_MODAL_EDIT'
// export const host = 'http://localhost:8080/ws'
export const host = 'https://hospitalcaretech.online/ws'
