export const EMAIL_AGAIN = 'Please check your email again *'
export const EMAIL_REQUIRE = 'Email is require *'
export const FIRSTNAME_AGAIN = 'Please check your first name again *'
export const FIRSTNAME_REQUIRE = 'First name is require *'
export const LASTNAME_AGAIN = 'Please check your last name again *'
export const LASTNAME_REQUIRE = 'Last name is require *'
export const PASSWORD_AGAIN = 'Please check your password again *'
export const PASSWORD_CONFIRM_AGAIN = 'Both password need to be the same *'
export const PASSWORD_CONFIRM_REQUIRE = 'Confirm password is require *'
export const PASSWORD_MESSAGE =
  'Least one alphabetic character, one digit, one special character and is between 8 and 20 characters'
export const PASSWORD_REQUIRE = 'Password is require *'
export const PHONE_AGAIN = 'Please check your phone again *'
export const PHONE_REQUIRE = 'Phone number is require *'
